fix: IPC on multiwindowed linux apps (fix #11171)
tauri-apps/tauri pull request #11236
Opened 2024-10-05 20:12 UTC by Ynng

closes #11171

- Fix ipc on multiwindowed linux apps
- Include window label in `InvokeRequest`
- Update the IPC handler to fetch webview based on the window label in `InvokeRequest`

2024-10-05 20:17 UTC, amrbashir commented
@Ynng thanks for investigating and making a PR, I wonder if we can fix this in `wry` instead.

2024-10-05 20:25 UTC, Ynng commented
> @Ynng thanks for investigating and making a PR, I wonder if we can fix this in `wry` instead.

As in fixing the underlying "Cannot register URI scheme xxx more than once"?

2024-10-08 05:10 UTC, amrbashir commented
thanks @Ynng, I have decided to incorporate the idea of this PR in wry instead, see https://github.com/tauri-apps/wry/pull/1384 and https://github.com/tauri-apps/tauri/pull/11268. Apologies for the inconvenience.

@lucasfernog maybe we should merge this as a fix for 2.0 because #11268 will require a minor bump.

2024-10-08 05:11 UTC, amrbashir requested changes

2024-10-08 05:11 UTC, amrbashir commented on crates/tauri/src/webview/mod.rs
> +  pub label: String,
if we are gonna merge this PR as temporary fix, we should avoid adding this field.

2024-10-08 05:11 UTC, amrbashir commented on crates/tauri/src/ipc/protocol.rs
> +    .ok_or("missing Tauri-Webview-Label header")?
could you also fix tests that are failing because of this?

2024-10-08 06:04 UTC, Ynng commented
Thanks @amrbashir for the proper fix in wry (tauri-apps/wry#1384 and #11268)!

Given that this PR introduces temporary changes across multiple files and a new field in `InvokeRequest`, I'm okay with closing it in favor of waiting for the wry-based solution.

2024-10-08 15:40 UTC, amrbashir commented
@Ynng This PR can still be merged to fix the current released minor, we just need the changes I requested

2024-10-12 02:50 UTC, amrbashir commented
thanks @Ynng , I will go ahead and close this then since https://github.com/tauri-apps/tauri/pull/11268 will be merged

2024-10-12 02:50 UTC, closed without merging