fix: successful response should have no body to a HEAD request, closes #11263
tauri-apps/tauri pull request #11264
Opened 2024-10-07 23:37 UTC by chrox

2024-10-07 23:55 UTC, amrbashir requested changes
Thank you, could you add a change file in `.changes` directory?

2024-10-08 00:09 UTC, chrox commented
> Thank you, could you add a change file in `.changes` directory?

OK. Done.

2024-10-08 00:59 UTC, amrbashir commented on .changes/change-pr-11264.md
> +fix: successful response should have no body to a HEAD request, closes #11263
```suggestion
Respond with empty body for `HEAD` requests to `asset` protocol
```

2024-10-08 01:00 UTC, amrbashir approved these changes
Thank you

2024-10-08 01:07 UTC, merged