feat(bundler): Add Debian package support for updater bundles
tauri-apps/tauri pull request #11562
Opened 2024-11-01 03:12 UTC by jLynx

## Description

This PR adds support for Debian (.deb) packages in the updater bundle system, allowing Debian packages to be included in the self-contained updater functionality alongside existing formats like AppImage, NSIS, and Windows MSI.

_Note: This PR relies on https://github.com/tauri-apps/plugins-workspace/pull/1991_

## Changes

- Added `PackageType::Deb` to the list of self-contained updater package types
- Modified the Linux bundler to handle both AppImage and Debian package formats
- Extended the updater bundle functionality to create tar.gz archives for Debian packages
- Updated signing functionality to include Debian packages
- Fixed JSON formatting in schema documentation examples

## Testing

I have tested the following scenarios:

1. Building a Debian package with updater enabled
2. Verifying the .deb archive creation for Debian packages
3. Confirming the signing process works correctly for Debian packages
4. Ensuring existing functionality for other package types remains unchanged

2024-11-03 21:31 UTC, jLynx commented
Removed support for .deb.tar.gz as requested by @FabianLars https://discord.com/channels/616186924390023171/1301285233991356506/1302596935101976616

2024-11-12 02:13 UTC, amrbashir reviewed
Could you also add a change file in .changes directory?

2024-11-12 23:25 UTC, amrbashir requested changes

2024-11-12 23:25 UTC, amrbashir commented on .changes/deb-updater-support.md
> +'@tauri-apps/bundler': minor:feat
```suggestion
'tauri-bundler': minor:feat
'tauri-cli': minor:feat
'@tauri-apps/cli': minor:feat
```

2024-11-12 23:25 UTC, amrbashir commented on .changes/deb-updater-support.md
> +Add support for Debian (`.deb`) packages in the updater bundle system, enabling self-contained updater functionality for Debian packages alongside existing formats like AppImage, NSIS, and Windows MS
```suggestion
Generate signature for `.deb` packages when `createUpdaterArtifacts` option is enabled.
```

2024-11-13 01:07 UTC, amrbashir approved these changes

2024-11-13 01:12 UTC, merged