feat: add support for injecting script into subframes (from wry)
tauri-apps/tauri pull request #11971
Opened 2024-12-14 05:02 UTC by Geometrically

This PR ports https://github.com/tauri-apps/wry/pull/1365 to Tauri/tauri-runtime-wry

2024-12-18 18:54 UTC, Norbiros approved these changes

2025-03-24 13:45 UTC, amrbashir requested changes
apologies for the late review, could you also add a change file in .changes directory?

2025-03-24 13:45 UTC, amrbashir commented on crates/tauri/src/webview/mod.rs
> +  pub fn initialization_script_for_main_only(mut self, script: &str, main_only: bool) -> Self {
This same method needs to be added on the `WebviewWindow` type as well.

2025-04-13 11:40 UTC, lucasfernog commented
oh looks like we already merged this on a separate PR: #/13076
thank you for your contribution!

2025-04-13 11:40 UTC, closed without merging