fix: fix panic caused by assert(removed_resource.is_none())
tauri-apps/tauri pull request #12000
Opened 2024-12-18 08:07 UTC by stringhandler

closes #11955

Fixes a panic caused by an assert when the resource random id has been used already

2024-12-18 14:46 UTC, amrbashir requested changes
Thank you, could you also add a change file in `.changes` directory?

2024-12-18 14:57 UTC, stringhandler commented
Added a file in `.changes`. From the contributing guide it seemed like this was unnecessary for bug fixes, but I might have misread it.

2024-12-18 15:31 UTC, amrbashir commented on .changes/fix-resource-id.md
> +`panic: assertion failed: removed_resource.is_none()`
```suggestion
Fixed a panic caused by an assert when the resource random id has been used already.
```

2024-12-23 14:05 UTC, amrbashir approved these changes

2024-12-23 14:11 UTC, merged