chore: fix crates.io link
tauri-apps/tauri pull request #12018
Opened 2024-12-20 17:51 UTC by ferreira-tb

Fix a link in the readme file.

2024-12-20 18:33 UTC, FabianLars approved these changes, later dismissed

2024-12-20 21:07 UTC, amrbashir approved these changes

2024-12-20 21:07 UTC, amrbashir commented
Thank you

2024-12-20 21:09 UTC, amrbashir requested changes

2024-12-20 21:09 UTC, amrbashir commented on crates/tauri-utils/README.md
Need to run `pnpm format`

2024-12-21 00:46 UTC, amrbashir approved these changes

2024-12-21 00:46 UTC, amrbashir commented
Thank you

2024-12-21 00:46 UTC, merged