Typing (api/os)
tauri-apps/tauri pull request #2558
Opened 2021-08-31 09:11 UTC by mq1

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding Issue #___
- [x] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

2021-08-31 09:16 UTC, amrbashir requested changes
Thanks for your work, can you also export these types ? 
```ts
export type {
	Platform,
	Arch
	OsType
}
```

2021-08-31 09:16 UTC, amrbashir commented on tooling/api/src/os.ts
> +type Type = 'Linux' | 'Darwin' | 'Windows_NT'
I think `OsType` might be a better name here.

2021-08-31 09:35 UTC, mq1 commented
done!

2021-08-31 09:48 UTC, amrbashir commented on tooling/api/src/os.ts
> +  return invokeTauriCommand<Type>({
```suggestion
async function type(): Promise<OsType> {
  return invokeTauriCommand<OsType>({
```

2021-08-31 09:49 UTC, amrbashir approved these changes

2021-09-21 19:23 UTC, lucasfernog approved these changes

2021-09-21 19:24 UTC, merged