docs: add information to reboot computer before using tauri
tauri-apps/tauri pull request #2710
Opened 2021-10-04 14:31 UTC by kimlimjustin

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [x] Docs
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**Other information:**

This PR adds information to recommend users to reboot their computer before using Tauri for everything to work perfectly.

2021-10-04 14:48 UTC, amrbashir requested changes
Thanks but this note should be all the way down before `## Continue` ? also use the Alert component.
```
<Alert type="note">
We recommend you reboot your computer before using Tauri for everything to work perfectly.
</Alert>
```

2021-10-04 15:11 UTC, amrbashir approved these changes

2021-10-05 10:20 UTC, nothingismagick commented
This had me wondering, until I realized it was just about Windows. This has literally been a thing for over 20 years, and I guess I assumed it was general knowledge. Thanks for the suggestion!!!

2021-10-05 10:22 UTC, nothingismagick commented on docs/getting-started/setup-windows.md
> +We recommend you reboot your computer before using Tauri for everything to work perfectly.
```suggestion
If you have problems of any kind after following these instructions, we recommend that you reboot your computer before developing a Tauri project to ensure that everything works as expected.
```

2021-10-05 10:54 UTC, nothingismagick approved these changes

2021-10-08 20:00 UTC, nothingismagick approved these changes

2021-10-11 13:16 UTC, merged