Improved docs for System Tray
tauri-apps/tauri pull request #3119
Opened 2021-12-26 23:56 UTC by ksnyde

Documentation only change which focuses on:

1. talks about Tauri's ability to configure icon for macOS and as long as similarly named `ico` file exists it'll work for Windows and Linux (this is missing and led me to believe I needed to use OS specific configs)
2. talks about ideal image sizes for the system icon per OS and maps that to the **Tauri CLI**'s `icon` command

2021-12-27 08:11 UTC, amrbashir requested changes

2021-12-27 08:11 UTC, amrbashir commented on docs/usage/guides/visual/system-tray.md
> +      "iconPath": "icons/tray.png",
Lets keep this as is, otherwise users will have duplicate icons with the same data, and they might forget to provide `.ico` version

2021-12-27 08:11 UTC, amrbashir commented on docs/usage/guides/visual/system-tray.md
> +The `iconAsTemplate` is a boolean value that determines whether the image represents a [template](https://developer.apple.com/documentation/appkit/nsimage/1520017-template?language=objc) image on mac
```suggestion
- The `iconAsTemplate` - _macOS only:_ is a boolean value that determines whether the image represents a [template](https://developer.apple.com/documentation/appkit/nsimage/1520017-template?language=objc) image on macOS.
```

2021-12-27 08:11 UTC, amrbashir commented on docs/usage/guides/visual/system-tray.md
> -The `iconPath` is pointed to a PNG file on macOS and Linux, and a `.ico` file must exist for Windows support.
I don't see why this needs to be moved into another section, the wording could be better though.

```suggestion
- The `iconPath` is a path to a PNG file which will be used on macOS and Linux. You also have to include a `.ico` with the same name for Windows and Tauri will automatically detect it.
```

2021-12-27 08:11 UTC, amrbashir commented on docs/usage/guides/visual/system-tray.md
> +> Note: if you're using the **Tauri CLI**'s [_icon_](https://tauri.studio/en/docs/api/cli#icon) command you'll already have the images you need. The generated `icons/icon.ico` has all image sizes you
This not necesary IMO, See my comment above. Although the note can be added after `iconPath` explanation above.

2022-02-05 03:47 UTC, lucasfernog commented
I'm closing this since we moved the docs entirely to the tauri-docs repo. Please open a PR in there to get these changes reviewed :)

2022-02-05 03:47 UTC, closed without merging