fix: add support for Time-Stamping Protocol for Windows codesigning (fix #3563)
tauri-apps/tauri pull request #3570
Opened 2022-02-28 07:32 UTC by gardc

### What kind of change does this PR introduce?

- [x] Bugfix
- [x] Feature
- [x] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information
First time contributing code to Tauri, so please feel free to let me know if there are any issues or something that could be improved.

2022-03-01 02:28 UTC, chippers commented
can you run `cargo +nightly fmt` on your branch so that we avoid formatting changes? it would also make it easier to review

2022-03-01 08:54 UTC, gardc commented
@chippers `cargo +nightly fmt` wasn't working properly for me, but I fixed the formatting in `sign.rs` which got changed for some reason.

2022-03-06 23:49 UTC, lucasfernog requested changes

2022-03-06 23:49 UTC, lucasfernog commented on .changes/bundler-add-tsp-signing.md
> +"tauri-cli": patch
```suggestion
"cli.rs": patch
"cli.js": patch
```

2022-03-06 23:49 UTC, lucasfernog commented on .changes/bundler-add-tsp-signing.md
> +"tauri-core": patch
```suggestion
"tauri": patch
```

2022-03-07 00:29 UTC, lucasfernog approved these changes

2022-03-07 00:29 UTC, merged

2022-03-07 00:30 UTC, lucasfernog commented
Thank you :heart: