feat(core): Expose wry and tao
tauri-apps/tauri pull request #3886
Opened 2022-04-11 19:39 UTC by dceddia

### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### Other information

The goal of this change is to be able to call tao APIs (like platform-native ones on WindowBuilder) from Tauri without having to separately depend on tao.

This change depends on this one in wry: https://github.com/tauri-apps/wry/pull/549

2022-04-11 19:52 UTC, amrbashir requested changes

2022-04-11 19:52 UTC, amrbashir commented on core/tauri-runtime-wry/src/lib.rs
> +pub use wry::tao;
```suggestion
pub use wry::application as tao;
```

2022-04-11 19:57 UTC, amrbashir approved these changes

2022-04-12 14:21 UTC, FabianLars commented
Doesn't this change would re-introduce the same problem as #3699?

2022-04-12 16:47 UTC, dceddia commented
Oh, bummer, yeah this looks like it's reintroducing that.

Maybe my issue can be solved another way. I'm using some APIs from `tao`, and right now tauri doesn't expose tao, so I'm depending on tao in my Cargo.toml directly. The problem then is if tauri updates to a newer version of tao, like what happened between rc.4 and rc.5 (or 6, I forget now) where tao went from 0.6.4 to 0.7.0, my app won't compile until I update that dependency.

[This forum post](https://users.rust-lang.org/t/add-a-crate-with-same-version-as-a-dependency-is-using/17389/12) sounds like what I want cargo to do, basically, "I don't care which `tao` you use, just make it the same as the one `tauri` uses". (Except transitively, because I guess tauri doesn't directly depend on tao) Maybe specifying `tao = ">=0"` will work for the time being?

2022-04-18 23:55 UTC, lucasfernog commented
Thanks for catching that Fabian. Too bad we can't expose tao and wry as it's not stable.

I face the same problem at work, we need to update everything all the time. It's ok but it can be annoying sometimes :/

2022-04-18 23:55 UTC, closed without merging