feat(bundler): allow bundling plugins with macOS applications
tauri-apps/tauri pull request #4138
Opened 2022-05-16 09:25 UTC by 0xVenge

### What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [x] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### Other information
This change allows bundling app extensions, like Safari extensions or content blockers, and is quite trivial. I think later on app extensions could be created with Rust and Tauri could provide a simple IPC channel between it and the host app to make these things even simpler to do.

2022-05-16 15:16 UTC, probablykasper approved these changes

2022-06-23 08:19 UTC, JonasKruckenberg commented
We require all commits to be signed across Tauri's repositories. Follow [this guide]() to s set up commit signing. Once all the commits in this PR are signed we can merge your contribution. Thanks for being part of our community!

2022-06-23 08:27 UTC, JonasKruckenberg requested changes
We require all commits to be signed across Tauri's repositories. Follow [this guide](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) to s set up commit signing. Once all the commits in this PR are signed we can merge your contribution. Thanks for being part of our community!

You also need to add a changefile explaining the feature you added.

2022-07-18 00:33 UTC, closed without merging

2023-01-04 10:39 UTC, andybin-cn commented
any update about this?  I need this feature🙏