fix: add a default icon to notifications on linux
tauri-apps/tauri pull request #4283
Opened 2022-06-07 02:27 UTC by betamos

Currently, the notification api allows an optional icon. This has no effect on Windows and MacOS, where the icon is always taken from the application. This change has no effect on those platforms, but sets a default icon based on the binary path, which ensures notifications, by default, uses the app's icon.

This icon is also shown in dev mode if the app is installed. Otherwise, it just displays no icon.

### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information

2022-06-07 14:43 UTC, lucasfernog commented on core/tauri/src/endpoints/notification.rs
> +    let icon = options
we should probably do this only on Linux with a `#[cfg]` guard.

2022-06-07 14:44 UTC, lucasfernog requested changes
Please add a change file, check out the `.changes` folder to see how to do it. Basically:

```markdown
---
"tauri": patch
---

Set notification icon to app icon on Linux.
```

2022-06-07 18:30 UTC, betamos commented on core/tauri/src/endpoints/notification.rs
> +    let icon = options
Resolved by using `auto_icon` instead.

2022-06-09 19:41 UTC, lucasfernog approved these changes

2022-06-09 19:42 UTC, merged