fix(api): fs/exists return type previously set to void when it should be boolean
tauri-apps/tauri pull request #5252
Opened 2022-09-21 09:46 UTC by keraf

Very small fix to the `fs/exists` method in the JS API, commit message should be explanatory enough 🙂 

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information
Question regarding the second point in the checklist of PRs: How does it work? The link to the doc is dead. Would love to add the file in this or future PRs if required.

2022-09-21 11:20 UTC, amrbashir requested changes
Thank you, could you also add a changefile in `.changes` folder?

2022-09-21 11:51 UTC, keraf commented
@amrbashir As mentioned in the bottom of the PR, the link to the docs is dead. Is there an up-to-date documentation you could point me to for how to proceed with change files? I'm unfamiliar with this process.

2022-09-21 11:53 UTC, FabianLars commented
Here's the file in question: https://github.com/tauri-apps/tauri/blob/f5f9f105f768c0a0b86009c4a9058ce28563211d/.changes/readme.md
Was deleted by accident in #4351

2022-09-21 11:55 UTC, amrbashir commented
> As mentioned in the bottom of the PR, the link to the docs is dead

Sorry about that, I didn't notice your note in the PR, I will fix that. and for now, use the link Fabian provided.

2022-09-21 12:02 UTC, keraf commented
Thanks! I have now added the change file.

2022-09-21 12:10 UTC, amrbashir approved these changes

2022-09-29 18:55 UTC, lucasfernog approved these changes

2022-09-29 18:55 UTC, merged