feat(core): expose additional_browser_args to window config (fix: #5757)
tauri-apps/tauri pull request #5799
Opened 2022-12-09 16:13 UTC by noamzaks

### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information
Could probably help various use cases, including mine in #5757.

[Discord thread](https://discord.com/channels/616186924390023171/1048227579066331216).

2022-12-09 16:25 UTC, amrbashir requested changes
Thank you, just a few nit-picks and should be good to go

2022-12-09 16:25 UTC, amrbashir commented on core/tauri-runtime/src/webview.rs
> +  /// Sets additional browser arguments on **Windows**.
```suggestion
  /// Sets additional browser arguments. **Windows Only**
```

2022-12-09 16:25 UTC, amrbashir commented on core/tauri-utils/src/config.rs
> +  /// Defines additional browser arguments on Windows.
```suggestion
  /// Defines additional browser arguments. **Windows Only**
```

2022-12-09 16:25 UTC, amrbashir commented on core/tauri/src/window.rs
> +  /// Set additional arguments for the webview on **Windows**.
```suggestion
  /// Set additional arguments for the webview. **Windows Only**
```

2022-12-09 16:25 UTC, amrbashir commented on tooling/api/src/window.ts
> +   * Additional arguments for the webview on Windows.
```suggestion
   * Additional arguments for the webview. **Windows Only**
```

2022-12-09 18:37 UTC, amrbashir submitted a review, later dismissed

2022-12-14 11:49 UTC, FabianLars commented
I think we should document the default value like we do in wry: https://docs.rs/wry/latest/x86_64-pc-windows-msvc/wry/webview/trait.WebViewBuilderExtWindows.html#tymethod.with_additional_browser_args

2022-12-14 14:46 UTC, lucasfernog approved these changes

2022-12-14 14:46 UTC, merged