feat(windows): implement `with_tooltip`
tauri-apps/tauri pull request #5938
Opened 2022-12-29 11:32 UTC by luoffei

### What kind of change does this PR introduce?
- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?
- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme]（https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md）.
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information

2022-12-30 01:02 UTC, amrbashir requested changes
Thank you for the contribution. 

The builder implementation is LGTM but, you also need to add `set_tooltip` on `SystemTrayHandle` structs.

2022-12-30 12:27 UTC, amrbashir requested changes

2022-12-30 12:27 UTC, amrbashir commented on core/tauri-runtime-wry/src/system_tray.rs
> +  #[cfg(any(windows, target_os = "macos"))]
No need for guard flags here I think, tao's `SystemTray::set_tooltip` exists on Linux but is a no-op.

2022-12-30 14:33 UTC, amrbashir requested changes

2022-12-30 14:33 UTC, amrbashir commented on core/tauri-runtime/src/menu.rs
> +  #[cfg(any(windows, target_os = "macos"))]
this also needs to be removed

2022-12-30 14:33 UTC, amrbashir commented on core/tauri/src/app/tray.rs
> +  #[cfg(any(windows, target_os = "macos"))]
also this

2022-12-30 14:33 UTC, amrbashir commented on core/tauri/src/app/tray.rs
> +      #[cfg(any(windows, target_os = "macos"))]
and this

2022-12-30 14:33 UTC, amrbashir commented on core/tauri/src/app/tray.rs
> +  #[cfg(any(windows, target_os = "macos"))]
and this

2022-12-30 14:33 UTC, amrbashir commented on core/tauri/src/app/tray.rs
> +    #[cfg(any(windows, target_os = "macos"))]
and this

2022-12-30 14:33 UTC, amrbashir commented on core/tauri/src/app/tray.rs
> +  #[cfg(any(windows, target_os = "macos"))]
and this

2022-12-30 17:21 UTC, amrbashir requested changes

2022-12-30 17:21 UTC, amrbashir commented on core/tauri/src/app/tray.rs
> +  ///
```suggestion
  ///
  /// ## Platform-specific:
  ///
  /// - **Linux:** Unsupported
  ///
```

2022-12-30 17:21 UTC, amrbashir commented on core/tauri/src/app/tray.rs
> +  /// Adds a tooltip for this tray icon.
```suggestion
  /// Set the tooltip for this tray icon.
  ///
  /// ## Platform-specific:
  ///
  /// - **Linux:** Unsupported
```

2022-12-31 12:49 UTC, amrbashir approved these changes, later dismissed
Thank you <3

2022-12-31 16:24 UTC, lucasfernog approved these changes
Nice work, thanks!

2022-12-31 16:24 UTC, merged