feat: dynamic settings menu (#6015)
tauri-apps/tauri pull request #6022
Opened 2023-01-09 14:45 UTC by lencx

### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information

2023-01-09 15:03 UTC, JonasKruckenberg commented
I really strongly dislike the naming scheme of `*_if` maybe we can come up with a better name here before merging this

2023-01-09 15:03 UTC, amrbashir requested changes

2023-01-09 15:03 UTC, amrbashir commented on core/tauri/src/app.rs
> +  pub fn system_tray_if(mut self, is_show: bool, tray_menu: tray::SystemTray) -> Self {
the second argument should be a closure that returns a system tray

2023-01-09 15:03 UTC, amrbashir commented on core/tauri/src/app.rs
> +  pub fn menu_if(mut self, is_show: bool, menu: Menu) -> Self {
the second argument should be a closure that returns a menu

2023-01-09 15:06 UTC, amrbashir commented
> I really strongly dislike the naming scheme of *_if maybe we can come up with a better name here before merging this

To me, it feels more idiomatic, and feels similar to `unwrap_or`. Also `druid` has a similar function https://docs.rs/druid/latest/druid/struct.MenuDesc.html#method.append_if

2023-01-09 15:07 UTC, lencx commented
> I really strongly dislike the naming scheme of `*_if` maybe we can come up with a better name here before merging this

How about `dyn_menu` and `dyn_system_tray`?

2023-01-09 15:11 UTC, lencx commented on core/tauri/src/app.rs
> +  pub fn system_tray_if(mut self, is_show: bool, tray_menu: tray::SystemTray) -> Self {
Can I ask why closures are recommended here?

2023-01-09 15:14 UTC, amrbashir commented on core/tauri/src/app.rs
> +  pub fn system_tray_if(mut self, is_show: bool, tray_menu: tray::SystemTray) -> Self {
because it will be lazily evaluated if the `is_show = true`, which means less memory consumption and allocations.

2023-01-09 15:18 UTC, lencx commented on core/tauri/src/app.rs
> +  pub fn system_tray_if(mut self, is_show: bool, tray_menu: tray::SystemTray) -> Self {
Thanks for the answer, I'll modify it right away.

2023-01-09 15:20 UTC, JonasKruckenberg commented
> How about dyn_menu and dyn_system_tray?

Hmm to me this feels worse than `_if` maybe amr is indeed right and the original is not that bad 🤔 
`add_system_tray_if` sounds a bit nicer to me, but I guess it's redundant so don't worry

2023-01-09 15:45 UTC, tk103331 reviewed
change the examples to use closure?

2023-01-09 15:55 UTC, lencx commented
> change the examples to use closure?

😅 I made a low-level mistake, false will not call the function, this is the most basic programming knowledge, I suddenly forgot.

2023-01-09 16:36 UTC, FabianLars commented
To be completely honest i don't see the value in this new api, but i also didn't see the problem in #6015. What's wrong with the standard builder pattern? (genuine question) You can do the same stuff with it already and this new api doesn't really feel rust-y too me 😅

2023-01-09 16:44 UTC, lencx commented
@FabianLars This pr is just a suggestion and can be turned off if team members see little value in it. Because its existence does reduce some insignificant workload. 😅

2023-01-09 16:50 UTC, amrbashir commented
this is a mere quality of life improvement to turn this:
```rs
let mut builder = tauri::Builder::default();
if show_menu {
	builder = builder.menu(Menu::default);
}
builder.build().unwrap();
```
into this:
```rs
tauri::Builder::default()
	.menu_if(show_menu, Menu::default)
	.build()
	.unwrap()
```

2023-01-09 16:54 UTC, amrbashir requested changes

2023-01-09 16:54 UTC, amrbashir commented on core/tauri/src/app.rs
> +  pub fn system_tray_if<F>(mut self, is_show: bool, tray_menu: F) -> Self
```suggestion
  pub fn system_tray_if<F>(mut self, condition: bool, tray_menu: F) -> Self
```

2023-01-09 16:54 UTC, amrbashir commented on core/tauri/src/app.rs
> +  pub fn menu_if<F>(mut self, is_show: bool, menu: F) -> Self
```suggestion
  pub fn menu_if<F>(mut self, condition: bool, menu: F) -> Self
```

2023-01-09 16:54 UTC, amrbashir commented on core/tauri/src/app.rs
> +  /// Dynamically sets the given system tray to be built before the app runs.
```suggestion
  /// Sets the given system tray to be built before the app runs if `condition` is `true`.
```

2023-01-09 16:54 UTC, amrbashir commented on core/tauri/src/app.rs
> +  /// Dynamically sets the menu to use on all windows.
```suggestion
  /// Sets the menu to use on all windows if `condition` is `true`.
```

2023-01-09 16:57 UTC, FabianLars commented
> this is a mere quality of life improvement to turn this:...

Yeah i got that, and i see the appeal, it's just something i feel like you don't often see in rust world. But if you guys like it then i'm fine with that. Just wanted to make you guys think about it a second time :)

2023-01-09 17:06 UTC, JonasKruckenberg commented
> this is a mere quality of life improvement to turn this:
> 
> ```rust
> let mut builder = tauri::Builder::default();
> if show_menu {
> 	builder = builder.menu(Menu::default);
> }
> builder.build().unwrap();
> ```
> 
> into this:
> 
> ```rust
> tauri::Builder::default()
> 	.menu_if(show_menu, Menu::default)
> 	.build()
> 	.unwrap()
> ```

I honestly don't think it's that big of a saving **and** thinking about it some more, this would open us up to adding conditional versions of almost *all* builder methods 🤔 So maybe @FabianLars has a point here and we should pass on this one.
Also removing something that mad it into the codebase is really hard. We should merge wisely

2023-01-09 17:09 UTC, amrbashir commented
> thinking about it some more, this would open us up to adding conditional versions of almost all builder methods

yeah right, didn't think about that!

2023-01-26 14:09 UTC, lucasfernog commented
I don't think we should do this tbh. As said earlier in the discussion, users can handle this by storing the builder in a variable. What could be nice in the future would be allowing `None` to be given as an argument, so you could do `.system_tray(if should_show { Some(tray) } else { None })`.

2023-01-26 21:23 UTC, lencx commented
This PR holds without breaking the existing api, and changing it to `Option` would indeed be a better way to go.

2023-01-27 09:52 UTC, closed without merging