fix(api): event name types
tauri-apps/tauri pull request #6318
Opened 2023-02-19 19:05 UTC by 2nthony

### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information

https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html

May a better dev experience with this type declaration, we can get code completion instead of `import { TauriEvent } from 'xxx'/event`, and the `TauriEvent["xxx"]` still works.

Tested in source code.

![image](https://user-images.githubusercontent.com/19513289/219969222-ac5df2a4-3336-4c51-8b60-49d475fc10fd.png)

![image](https://user-images.githubusercontent.com/19513289/219969186-4c43274c-a7fa-4f91-8410-9d422e80a493.png)

2023-02-19 22:40 UTC, amrbashir requested changes

2023-02-19 22:40 UTC, amrbashir commented on tooling/api/src/event.ts
> +export type EventName = `${TauriEvent}`
We also need to allow `string` type to be passed, `TauriEvent` is just for auto-completion purposes and not enforce a variant of it. I think we should be using this little trick from type-fest's [`LiteralUnion`](https://github.com/sindresorhus/type-fest/blob/main/source/literal-union.d.ts) instead

```suggestion
export type EventName = `${TauriEvent}` | (string & Record<never, never>)
```

2023-02-20 12:36 UTC, amrbashir approved these changes

2023-03-09 12:36 UTC, 2nthony commented
Will this merge or not?🤔 @amrbashir

2023-03-09 12:40 UTC, amrbashir commented
Sorry for the delay but the lead developer is on vacation atm and it is waiting for his approval.

2023-03-16 12:16 UTC, lucasfernog approved these changes

2023-03-16 12:16 UTC, merged