feat: add config links to json schema (closes #5479)
tauri-apps/tauri pull request #6356
Opened 2023-02-24 14:16 UTC by ShaunSHamilton

### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### Other information

Closes #5479

_I am unsure about the need for any package version bumps - this is really just a docs change_ 🤷‍♂️ 

I considered a few approaches for this, but, after fooling around for too long, I decided to just submit the simple solution.

**Future Considerations**

- The links could be automatically generated (updated) - making maintenance easier
- Certain configs did not get links to look as expected (they are overwritten):
  - The `WindowsConfig` is not updated, because it is defined as a `Vec`:

```rust
  /// The windows configuration.
  #[serde(default)]
  pub windows: Vec<WindowConfig>,
```

As such, the doc comment above the field is taken - contrast other definitions where the struct definition doc comment overwrites the field doc comment.

- It would be nice to have full markdown support in the tooltip using the `markdownDescription` property. However, this is a VSCode field, and is not defined in the JSON Schema. So, the implementation would involve more hacking as the `schemars::schema::Metadata` struct does not include a `markdown_description` field.

2023-02-28 13:12 UTC, amrbashir requested changes
Thank you for your contribution. 

While this is a good start, we definitely should also take this opportunity to add links for each field as well, for example this https://tauri.app/v1/api/config/#cliarg.numberofvalues

> The `WindowsConfig` is not updated, because it is defined as a Vec

what do you mean about that? you can use this `https://tauri.app/v1/api/config/#tauriconfig.windows` for the `windows` field and this link `https://tauri.app/v1/api/config/#windowconfig` on the struct and both will show as expected.

2023-02-28 13:23 UTC, ShaunSHamilton commented
> what do you mean about that?

```rust
/// Doc comment ignored on `TauriConfig.windows`
struct WindowsConfig {}
/// Doc comment used for `TauriConfig.bundle`
struct BundleConfig {}
struct TauriConfig {
  /// Doc comment used, because type `WindowsConfig` is not base type - `Vec<...>` is
  windows: Vec<WindowsConfig>;
  /// Doc comment overridden, because priority is given to comment above base type - `BundleConfig`
  bundle: BundleConfig;
}
```

---

However, this is now moot, because I will add links to all fields.

2023-02-28 13:29 UTC, amrbashir commented
I see what you mean, it is inconsistent, but we have to make the best of it

2023-02-28 16:56 UTC, FabianLars commented
@lorenzolewis do you think this is something that should wait for the new docs?

2023-02-28 17:14 UTC, ShaunSHamilton commented
One problem with the current docs is it would result in a self reference:

<img width="642" alt="image" src="https://user-images.githubusercontent.com/51722130/221927322-b1cd6510-1ec0-4e1e-95ea-9691cf4bec95.png">

2023-02-28 17:26 UTC, FabianLars commented
As long as they all use a similar format that should be easy to strip in the doc generator

2023-02-28 18:21 UTC, lorenzolewis commented
I'm not familiar with how exactly this is generated (nor all the details of the schema spec) but is there any support for an actual link object? I want to avoid putting information in a generic "description".  

Some things to look at are the spec for hyper-schemas, particularly the `links` object: https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-hyperschema-01#section-5.2

An example of this in practice I found here: https://apisyouwonthate.com/blog/getting-started-with-json-hyper-schema#json-hyper-schema

I'm curious at what TypeScript is using that generates the links in the screenshot below. Are those just hard-coded links in the comment part of the schema? Or are they using a specific field.

Then that leads me to ask if whatever tooling we're using to extract the info from the .rs files into the appropriate schema supports it. 

<img width="511" alt="Screenshot 2023-02-28 at 18 02 32" src="https://user-images.githubusercontent.com/15347255/221941147-7720e680-b5d4-47d0-ad6d-0d0ff3f3c685.png">

2023-02-28 20:04 UTC, ShaunSHamilton commented
> I'm curious at what TypeScript is using that generates the links in the screenshot below. Are those just hard-coded links in the comment part of the schema? 

https://github.com/SchemaStore/schemastore/blob/b4eccc2fb5ad76fd9c0a70fa67228e5d65e2b562/src/schemas/json/tsconfig.json#L693-L705

> Then that leads me to ask if whatever tooling we're using to extract the info from the .rs files into the appropriate schema supports it.

As said in the PR description:

> It would be nice to have full markdown support in the tooltip using the `markdownDescription` property. However, this is a VSCode field, and is not defined in the JSON Schema. So, the implementation would involve more hacking as the `schemars::schema::Metadata` struct does not include a `markdown_description` field.

2023-03-01 12:34 UTC, lorenzolewis commented
I checked and schemars doesn't have support for that hyper protocol which adds the links support.

I think it would be better to instead link out to a single page on all the objects like https://tauri.app/v1/api/config. That would be a lot easier to maintain both in this repo I'd imagine. Plus we're also going to break all of these URLs this summer most likely with some changes coming to the website.

2023-03-02 14:51 UTC, ShaunSHamilton commented
Thank you for the input, maintainers.

Could I get clarification on which direction this feature should go?

**Discussed**

a) Discard current feature, pending new docs
b) Add specific property links to every field
c) Add the same link (`/config`) to every field

2023-03-03 11:20 UTC, lorenzolewis commented
I'd be a proponent of c) as it would still give you a place in IDEs to get more info without increasing maintenance and gives docs the flexibility to change URL paths. @tauri-apps/wg-tauri are the ones who ultimately maintain this repo so will defer to them for a decision. 

RE: Which path to use if going with option c: https://tauri.app as the path previously stated **will** be changing this spring/summer.

Edit: And thank you @ShaunSHamilton for outlining the discussed points, very much appreciated <3

2023-03-17 16:17 UTC, lucasfernog approved these changes

2023-03-17 16:17 UTC, merged