feat(core/tauri): add try_get_item for SystemTray and WindowMenu, closes #5491
tauri-apps/tauri pull request #6408
Opened 2023-03-07 15:39 UTC by mrjackwills

### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### Other information

I opened an issue, [seen here](https://github.com/tauri-apps/tauri/issues/5491), wondering whether Tauri should have methods to return Option<T> for System Tray & and Menu Items, rather than panicking on `get_item(x)`. This PR addressed that issue

2023-03-07 15:56 UTC, amrbashir requested changes

2023-03-07 15:56 UTC, amrbashir commented on .changes/minor.md
> +Added fn "try_get_item" in tauri core window menu.
```suggestion
Add `MenuHandle::try_get_item` and `SystemTrayHandle::try_get_item`.
```

2023-03-07 15:56 UTC, amrbashir commented on core/tauri/src/app/tray.rs
> +  /// Gets an Optional<handle> to the menu item that has the specified `id`.
```suggestion
  /// Attempts to get a handle to the menu item that has the specified `id`, return an error if `id` is not found.
```

2023-03-07 15:56 UTC, amrbashir commented on core/tauri/src/window/menu.rs
> +  /// Gets an Option<handle> to the menu item that has the specified `id`.
```suggestion
  /// Attempts to get a handle to the menu item that has the specified `id`, return an error if `id` is not found.
```

2023-03-07 16:05 UTC, amrbashir submitted a review, later dismissed
Thank you

2023-03-07 16:13 UTC, mrjackwills commented
> Thank you

I used the GitHub site to commit the suggestions, is that now an issue with commits being signed? As I didn't have a ssh signing key set up on my profile

2023-03-07 16:24 UTC, amrbashir commented
you can squash all commits locally and force push the branch

2023-03-07 16:52 UTC, mrjackwills commented
> 
Thanks, although this is where git goes over my head, I am slightly at a loss as what to do

2023-03-07 17:00 UTC, amrbashir commented
```sh
git reset HEAD~6 # reset the last 6 commits but keep the changes
git add . # stage all changes
git commit -m "<your-commit-message-here>" # commit changes
git push --force # force push
```

2023-03-07 17:02 UTC, mrjackwills commented
> ```shell
> git reset HEAD~6 # reset the last 6 commits but keep the changes
> git add . # stage all changes
> git commit -m "<your-commit-message-here>" # commit changes
> git push --force # force push
> ```

Thankyou!

I think I might have fixed it, I really need to read up on git

2023-05-12 12:37 UTC, amrbashir requested changes

2023-05-12 12:37 UTC, amrbashir commented on .changes/tray_get_item.md
> +Add `MenuHandle::try_get_item` and `SystemTrayHandle::try_get_item` which returns a `Result` instead of panicking.
```suggestion
Add `MenuHandle::try_get_item` and `SystemTrayHandle::try_get_item` which returns a `Option` instead of panicking.
```

2023-05-12 12:37 UTC, amrbashir approved these changes

2023-05-12 13:15 UTC, merged