fix(cli): use `npm run tauri -- foo` for correctly passing args to tauri
tauri-apps/tauri pull request #6448
Opened 2023-03-14 11:55 UTC by meowtec

### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [x] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information

If use `npm run tauri android init` for generating Android project, we will get some error like this when `run dev`:

```
error: unexpected argument 'aarch64' found
Usage: npm run tauri android android-studio-script [OPTIONS]
For more information, try '--help'.
```

Executed commandis:

```
npm run  tauri android android-studio-script --target aarch64
```

NPM will consume argument `--target`, then pass `android android-studio-script aarch64` to tauri.

When using npm, we should use `--` for passing args into tauri.

Instead, we should use `npm run  tauri -- android android-studio-script --target aarch64`.

The minimum case is `npm run tauri -v` which will output NPM version.

I have tested with `pnpm` and `yarn`, 

Also see https://github.com/npm/npm/pull/5518

2023-03-14 12:08 UTC, amrbashir requested changes

2023-03-14 12:08 UTC, amrbashir commented on .github/ISSUE_TEMPLATE/bug_report.yml
> -      description: "Output of `npm run tauri info` or `cargo tauri info`"
this change is not needed since `npm run tauri info` works just fine

2023-03-14 12:08 UTC, amrbashir commented on ARCHITECTURE.md
> -npm run tauri dev
ditto

2023-03-14 12:08 UTC, amrbashir commented on examples/api/README.md
> -$ npm run tauri dev
ditto

2023-03-14 12:08 UTC, amrbashir commented on examples/resources/README.md
> -$ npm run tauri dev
ditto

2023-03-14 12:08 UTC, amrbashir commented on examples/sidecar/README.md
> -$ npm run tauri dev
ditto

2023-03-14 14:23 UTC, amrbashir submitted a review, later dismissed

2023-03-14 14:27 UTC, FabianLars commented
Judging from this single example:
> npm run  tauri android android-studio-script --target aarch64

I don't think this is something that needs changes inside tauri right? Aren't we just talking about this:
```rs
npm run tauri android android-studio-script -- --target aarch64
```
(note the extra `--`)

I mean, this is an issue with all commands (including desktop ones) so wouldn't we just make it inconsistent with this change?

Sorry if i'm missing something obvious here.

2023-03-14 15:04 UTC, meowtec commented
@FabianLars Mobile is special: 

> Judging from this single example:
> 
> > npm run  tauri android android-studio-script --target aarch64
> 
> I don't think this is something that needs changes inside tauri right? Aren't we just talking about this:
> 
> ```rust
> npm run tauri android android-studio-script -- --target aarch64
> ```
> 
> (note the extra `--`)
> 
> I mean, this is an issue with all commands (including desktop ones) so wouldn't we just make it inconsistent with this change?
> 
> Sorry if i'm missing something obvious here.

For desktop, it is simple to add `--` before arguments. (And there should be some alert / advice in docs, in the future)

While mobile is different: the command `...android-studio-script --target ...` is automatically generated into Android project by `android init` command, and executed by gradle, not explicitly / manually.

2023-03-16 11:38 UTC, lucasfernog approved these changes

2023-03-16 12:27 UTC, merged