feat(core): add IPC channel
tauri-apps/tauri pull request #6813
Opened 2023-04-27 20:11 UTC by lucasfernog

### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information

2023-04-28 04:49 UTC, wusyong reviewed
Is this mobile only feature?

2023-04-28 11:36 UTC, lucasfernog commented
> Is this mobile only feature?

I've also implemented it for desktop (it can easily be backported to v1) though the main idea here is to use it to send events from the Kotlin and Swift sides to the webview (eventually we'll also need a communication channel between mobile and Rust, but that's a little complicated since it involves static variables).

2023-04-28 14:22 UTC, JonasKruckenberg commented
Is this part of the public API?

2023-05-01 17:20 UTC, lucasfernog commented
Yeah it is part of the public API @JonasKruckenberg

2023-05-06 17:46 UTC, chippers requested changes
I'm not fully up to date with mobile, but I see what you are trying to do with the channel communication here.

Only suggestion would be to cut the channel prefix once, instead of splitting on the string and grabbing the second.

2023-05-06 19:07 UTC, chippers submitted a review, later dismissed

2023-05-06 19:51 UTC, chippers approved these changes, later dismissed

2023-05-06 20:56 UTC, JonasKruckenberg commented
Can we hold off on merging this until I had the chance to review it tomorrow?

2023-05-06 21:01 UTC, lucasfernog commented
Sure @JonasKruckenberg

2023-05-09 14:18 UTC, JonasKruckenberg requested changes

2023-05-09 14:18 UTC, JonasKruckenberg commented on core/tauri/src/api/ipc.rs
> +        .ok();
Maybe use `value.split_once(CHANNEL_PREFIX)`

2023-05-09 14:18 UTC, JonasKruckenberg commented on tooling/api/src/tauri.ts
> +class Channel {
I would refactor this to be more similar to the `Websocket` or `BroadcastChannel` api i.e. the constructor takes no arguments and you can listen to events by overriding the `on message` property or calling `.addEventListener('message', () => {})`

2023-05-09 15:12 UTC, lucasfernog commented on core/tauri/src/api/ipc.rs
> +        .ok();
Pushed.

2023-05-09 15:15 UTC, lucasfernog commented on tooling/api/src/tauri.ts
> +class Channel {
Good idea, pushed.

2023-05-11 06:15 UTC, wusyong approved these changes

2023-05-11 08:16 UTC, JonasKruckenberg approved these changes

2023-05-11 10:25 UTC, merged