fix(core): Send updater status events when default dialog is enabled, closes #7128
tauri-apps/tauri pull request #7157
Opened 2023-06-07 13:53 UTC by FabianLars

I'm not sure if i catched everything, quite tricky to grasp the whole flow here tbh and like we said in the issue i didn't do much more than the bare minimum here.

### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### Other information

2023-06-07 14:26 UTC, amrbashir requested changes

2023-06-07 14:26 UTC, amrbashir commented on core/tauri/src/updater/mod.rs
> +        } else if updater_config.dialog {
```suggestion
        if !updater.should_update {
          send_status_update(&handle, UpdaterEvent::AlreadyUpToDate);
        }
        if updater_config.dialog {
```

2023-06-07 14:57 UTC, FabianLars commented on core/tauri/src/updater/mod.rs
> +        } else if updater_config.dialog {
This would change the logic to always install the update even if it doesn't have to. If we don't want to have an if/else we can have 2 ifs, first one with `if !updater.should_update`, second one with `if updater.should_update && updater_config.dialog` (the old one) - this is what i first wanted to push.

Alternatively an early return if we don't wanna check for updater.should_update twice

2023-06-07 20:30 UTC, lucasfernog commented on core/tauri/src/updater/mod.rs
> +        } else if updater_config.dialog {
I don't see the issue with the logic in the PR. What is wrong with the if/else?

2023-06-08 11:14 UTC, amrbashir commented on core/tauri/src/updater/mod.rs
> +        } else if updater_config.dialog {
nvm my bad, I misinterpreted the logic

2023-06-08 11:14 UTC, amrbashir submitted a review, later dismissed

2023-06-08 12:38 UTC, lucasfernog requested changes

2023-06-08 12:38 UTC, lucasfernog commented on core/tauri/src/updater/mod.rs
> +      send_status_update(&update.app, UpdaterEvent::Error(err.to_string()));
It's ok for `prompt_for_install` to return an error, the caller already checks the error and emits the event.

2023-06-11 18:56 UTC, lucasfernog approved these changes

2023-06-13 11:05 UTC, merged