fix(core): Fix updater not being able to launch installers requiring elevation (fix: #7184)
tauri-apps/tauri pull request #7185
Opened 2023-06-12 16:43 UTC by Raphiiko

### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information

This PR should fix the issue posted in #7184. I am not quite sure if this is the correct solution, but it seems to fix the problem for me. 

Of course this does not solve the problem for existing builds, but I don't see a way for that to be fixed. Users will have to update once by launching the old version as administrator in order to update, or by reinstalling the new version.

2023-06-12 23:56 UTC, Raphiiko commented
I am converting this back to a draft because while it occasionally works, the behaviour still seems unreliable.

2023-06-13 17:23 UTC, amrbashir requested changes
thanks for you contribution

2023-06-13 17:23 UTC, amrbashir commented on core/tauri/src/updater/core.rs
> +        .args(&["/C", "start", "", found_path.as_os_str().to_str().unwrap()])
could you change this to use `powershell` instead? you will need to determine powershell path using `SYSTEMROOT` env var, move line 794 to line 715 and then do something similar  to line 795

2023-06-13 17:36 UTC, amrbashir commented on core/tauri/src/updater/core.rs
> +use windows::Win32::System::Threading::DETACHED_PROCESS;
from my testings, `DETACHEDPROCESS` was not needed when invoking `cmd` or `powershell` because they bother will call either `start` or `Start-Process` which will launch the installer in a detached process already.

2023-06-19 14:55 UTC, Raphiiko commented on core/tauri/src/updater/core.rs
> +        .args(&["/C", "start", "", found_path.as_os_str().to_str().unwrap()])
Woops, my bad, this had fallen off my radar completely. Thanks for updating my pr.

2023-06-19 15:08 UTC, amrbashir commented on core/tauri/src/updater/core.rs
> +        .args(&["/C", "start", "", found_path.as_os_str().to_str().unwrap()])
Don't worry about it, thanks for your contribution

2023-06-19 15:10 UTC, amrbashir approved these changes

2023-06-19 15:11 UTC, merged