refactor(cli): cleanup info command
tauri-apps/tauri pull request #7204
Opened 2023-06-14 17:20 UTC by amrbashir

### What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information

2023-06-15 11:33 UTC, lucasfernog commented on tooling/cli/src/info/packages_rust.rs
> +          "🦀",
I would avoid using this.. I only see a question mark :D

2023-06-15 12:25 UTC, amrbashir commented on tooling/cli/src/info/packages_rust.rs
> +          "🦀",
lol this is just an emoji, I was more concerned about the Node.js one, I will revert theses changes anyways, I will add them later if I find a good way to have a fallback

2023-06-15 12:26 UTC, amrbashir commented on tooling/cli/src/info/packages_nodejs.rs
> +            "".green(),
```suggestion
            "[NPM]".dimmed(),
```

2023-06-15 12:26 UTC, amrbashir commented on tooling/cli/src/info/packages_rust.rs
> +          "🦀",
```suggestion
          "[RUST]".dimmed(),
```

2023-09-14 17:37 UTC, martinfrances107 requested changes

2023-09-14 17:37 UTC, martinfrances107 commented on tooling/cli/src/info/packages_rust.rs
> +          let (package, version) = out.split_once(" ").unwrap_or_default();
```suggestion
          let (package, version) = out.split_once(' ').unwrap_or_default();
```

2023-09-14 17:37 UTC, martinfrances107 commented on tooling/cli/src/info/packages_rust.rs
> +          let (package, version) = out.split_once(" ").unwrap_or_default();
fixes a clippy warning

2023-09-14 17:37 UTC, martinfrances107 commented on tooling/cli/src/info/packages_rust.rs
> +            version.split_once("\n").unwrap_or_default().0,
```suggestion
            version.split_once('\n').unwrap_or_default().0,
```

2023-09-14 17:37 UTC, martinfrances107 commented on tooling/cli/src/info/packages_rust.rs
> +            version.split_once("\n").unwrap_or_default().0,
second clippy fix

2023-10-17 16:04 UTC, lucasfernog approved these changes

2023-10-17 16:10 UTC, merged