feat: add visible_on_all_workspaces, closes #6589
tauri-apps/tauri pull request #7437
Opened 2023-07-17 14:16 UTC by krzykro2

### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information
It's my first PR to Tauri, please be gentle. I basically added `visible_on_all_workspaces` to all the places where I found `always_on_top`. Haven't found any tests for `always_on_top` so haven't added any for my feature. Tested locally on my Linux and works great (given the Tao implementation I would assume it should work great on Mac also).

2023-07-20 23:59 UTC, amrbashir requested changes
LGTM, thanks for contribution, could you also add a change file in `.changes`?

2023-07-21 10:20 UTC, krzykro2 commented
> Thanks for contribution, could you run `cargo fmt` and add a change file in `.changes`?

Done. PTAL.

2023-07-24 16:41 UTC, amrbashir requested changes
Thanks

2023-07-24 16:41 UTC, amrbashir commented on core/tauri/src/window.rs
> +  /// Determines if this window should be visible on all workspaces or virtual desktops.
```suggestion
  /// Sets whether the window should be visible on all workspaces or virtual desktops.
```

2023-07-24 16:41 UTC, amrbashir commented on core/tauri-utils/src/config.rs
> +  /// Whether the window should be visible on all workspaces.
```suggestion
  /// Whether the window should be visible on all workspaces or virtual desktops.
```

2023-07-24 16:41 UTC, amrbashir commented on core/tauri-runtime/src/webview.rs
> +  /// Whether the window should be visible on all workspaces.
```suggestion
  /// Whether the window should be visible on all workspaces or virtual desktops.
```

2023-07-24 16:41 UTC, amrbashir commented on .changes/add-visible-on-all-workspaces.md
> +`Window`, and `WindowConfig`.
```suggestion
---
"tauri": 'minor:feat'
"tauri-runtime": 'minor'
"tauri-utils": 'minor:feat'
---

Added `visible_on_all_workspaces` configuration option to `WindowBuilder`, `Window`, and `WindowConfig`.
```

2023-07-24 16:41 UTC, amrbashir submitted a review, later dismissed

2023-07-24 16:53 UTC, amrbashir commented
Oh looks like you didn't sign some of your commits and I can't merge the PR unless they are signed. You need to setup [commit signing](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits), then you can sign past commit like [this](https://superuser.com/questions/397149/can-you-gpg-sign-old-commits/1123928#1123928) for example.

2023-07-24 16:54 UTC, amrbashir commented on core/tauri-config-schema/schema.json
> +          "description": "Whether the window should be visible on all workspaces.",
```suggestion
          "description": "Whether the window should be visible on all workspaces or virtual desktops.",
```

2023-07-24 16:54 UTC, amrbashir commented on tooling/cli/schema.json
> +          "description": "Whether the window should be visible on all workspaces.",
```suggestion
          "description": "Whether the window should be visible on all workspaces or virtual desktops.",
```

2023-07-24 17:00 UTC, krzykro2 commented
I might have failed at git :facepalm: 

I managed to successfully sign my old commit by rebasing back onto dev, however your commit seems to be unsigned now?

2023-07-25 14:34 UTC, amrbashir requested changes

2023-07-25 14:34 UTC, amrbashir commented on core/tauri-config-schema/schema.json
> +          "description": "Whether the window should be visible on all workspaces.",
```suggestion
          "description": "Whether the window should be visible on all workspaces or virtual desktops.",
```

2023-07-25 14:34 UTC, amrbashir commented on tooling/cli/schema.json
> +          "description": "Whether the window should be visible on all workspaces.",
```suggestion
          "description": "Whether the window should be visible on all workspaces or virtual desktops.",
```

2023-07-25 14:34 UTC, amrbashir approved these changes

2023-07-26 11:38 UTC, merged