fix: rpath missing from app, closes #7710
tauri-apps/tauri pull request #7773
Opened 2023-09-07 14:37 UTC by tr3ysmith

### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ X] No

### Other information
#7710

2023-09-15 06:54 UTC, Brendonovich commented
Seems like this also closes #7480. Symlinks in the `Frameworks` folder weren't being preserved but using this PR they are.

2023-09-15 09:06 UTC, afonsojramos approved these changes

2023-09-15 15:14 UTC, lucasfernog requested changes

2023-09-15 15:14 UTC, lucasfernog commented on core/tauri-build/src/lib.rs
> +      println!("cargo:rustc-link-arg=-Wl,-rpath,@executable_path/../Frameworks");
I assume this needs to be set to a different value on development, since we won't be running inside the .app bundle.

2023-09-15 15:15 UTC, lucasfernog commented
Can you rebase your branch to sign the [`ef8a58d` ](https://github.com/tauri-apps/tauri/pull/7773/commits/ef8a58df7dd8ff5cdbcb34eefb59e7ab03566cb8) commit?

2023-09-15 15:31 UTC, tr3ysmith commented on core/tauri-build/src/lib.rs
> +      println!("cargo:rustc-link-arg=-Wl,-rpath,@executable_path/../Frameworks");
So in my specific case, on our project, our Framework we're including comes from another library crate, so in my build script I have a function that goes and fetches it and then puts it in the target/Frameworks folder if `debug_assertions` is true. This basically works because that folder path is automatically included in the search path of the binary. Maybe we just need to automatically do that similar to how the resources folder is done?

2023-09-15 15:47 UTC, tr3ysmith commented
> Can you rebase your branch to sign the [`ef8a58d` ](https://github.com/tauri-apps/tauri/pull/7773/commits/ef8a58df7dd8ff5cdbcb34eefb59e7ab03566cb8) commit?

Should be good now

2023-09-19 12:26 UTC, lucasfernog commented on core/tauri-build/src/lib.rs
> +      println!("cargo:rustc-link-arg=-Wl,-rpath,@executable_path/../Frameworks");
Yeah sounds good to me

2023-09-19 15:58 UTC, tr3ysmith commented on core/tauri-build/src/lib.rs
> +      println!("cargo:rustc-link-arg=-Wl,-rpath,@executable_path/../Frameworks");
@lucasfernog are you able to point me in the right direction on where this should be implemented? I'd be happy to do it, but I'm assuming its in a different spot?

2023-09-20 05:35 UTC, tweidinger commented
Only concerns from sec perspective would be if `@executable_path/../Frameworks` is (world/all users) writeable, which from my understanding is not the case for apps properly deployed in macos (development seems a little different) and the application loading the relative libraries is not a suid binary, which is very rarely the case for a tauri application.

I think this would need to be documented for MacOS apps as risks for privilege escalation in case some privileged calls/libs/permissions are used/called from the Tauri app otherwise LGTM

2023-09-20 10:56 UTC, tr3ysmith commented
> Only concerns from sec perspective would be if `@executable_path/../Frameworks` is (world/all users) writeable, which from my understanding is not the case for apps properly deployed in macos (development seems a little different) and the application loading the relative libraries is not a suid binary, which is very rarely the case for a tauri application.
> 
> 
> 
> I think this would need to be documented for MacOS apps as risks for privilege escalation in case some privileged calls/libs/permissions are used/called from the Tauri app otherwise LGTM

No it would not be writable, anything inside the app package once signed cannot be modified otherwise the code signing is invalid.

2023-09-21 18:12 UTC, lucasfernog commented
@tr3ysmith can you double check my latest commit and see if [`af13f20` (#7773)](https://github.com/tauri-apps/tauri/pull/7773/commits/af13f20965c6b6c8a0d72036b7494d3870c1c2bd) works fine on your setup?

2023-09-21 18:17 UTC, lucasfernog commented on core/tauri-build/src/lib.rs
> +      println!("cargo:rustc-link-arg=-Wl,-rpath,@executable_path/../Frameworks");
pushed it :)

2023-09-22 12:34 UTC, tr3ysmith commented
> @tr3ysmith can you double check my latest commit and see if [`af13f20` (#7773)](https://github.com/tauri-apps/tauri/pull/7773/commits/af13f20965c6b6c8a0d72036b7494d3870c1c2bd) works fine on your setup?

Yeah that seems to work great, I was able to remove my build script and it worked.

2023-09-24 22:10 UTC, lucasfernog approved these changes

2023-09-24 22:11 UTC, merged