fix: (cli) format plugin string to snake case, closes #8017
tauri-apps/tauri pull request #8149
Opened 2023-11-01 02:21 UTC by vasfvitor

- [x] Bugfix
- [x] No breaking change

Is that it?

2023-11-06 19:41 UTC, amrbashir requested changes
Thanks for your contribution, Can you also add a change file in `.changes` directory?

2023-11-07 01:44 UTC, vasfvitor commented
Done. Anything else?

2023-11-07 13:36 UTC, lucasfernog commented on .changes/cli-plugin-name-snake-case.md
> +'tauri-cli': 'patch:bug'
```suggestion
'tauri-cli': 'patch:bug'
'@tauri-apps/cli': 'patch:bug'
```

2023-11-07 16:24 UTC, lucasfernog approved these changes

2023-11-07 16:24 UTC, lucasfernog commented
We actually use the heck crate to convert cases but the replace here is ok.

2023-11-07 16:53 UTC, vasfvitor commented
> We actually use the heck crate to convert cases but the replace here is ok.

Thanks for mentioning it. I should've stick to my guns. I did see `to_snake_case() `around but didn't want to import it.

2023-11-07 17:53 UTC, amrbashir approved these changes

2023-11-08 01:56 UTC, merged