fix(cli): invalid plugin template
tauri-apps/tauri pull request #8161
Opened 2023-11-01 15:27 UTC by lucasfernog

### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information

2023-11-06 19:52 UTC, amrbashir requested changes

2023-11-06 19:52 UTC, amrbashir commented on tooling/cli/templates/plugin/__example-api/tauri-app/vite.config.js
> +    },
let's remove all of this, not needed

2023-11-06 19:52 UTC, amrbashir commented on tooling/cli/templates/plugin/__example-api/tauri-app/vite.config.js
> +    'localhost'
```suggestion
  const mobile = !!/android|ios/.exec(process.env.TAURI_ENV_PLATFORM);
```

2023-11-06 19:52 UTC, amrbashir commented on tooling/cli/templates/plugin/__example-api/tauri-app/vite.config.js
> +      },
```suggestion
    server: {
    port: 1420,
    strictPort: true,
    host: mobile ? "0.0.0.0" : false,
    hmr: mobile
      ? {
          protocol: "ws",
          host: await internalIpV4(),
          port: 1421,
        }
      : undefined,
  },	
```

2023-11-07 12:17 UTC, FabianLars commented
i think `internal-ip` is missing from the termplate's package.json

2023-11-07 13:00 UTC, lucasfernog commented
I wonder how the hell it worked on my demo plugin test.

2023-11-07 17:53 UTC, amrbashir approved these changes

2023-11-08 01:56 UTC, merged