fix(bundler): migrate WebView2 offline installer to shorturl
tauri-apps/tauri pull request #8292
Opened 2023-11-23 05:12 UTC by i-c-b

### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information

2023-11-23 14:09 UTC, amrbashir requested changes

2023-11-23 14:09 UTC, amrbashir commented on tooling/bundler/src/bundle/windows/msi/wix.rs
> +      std::fs::write(&webview2_installer_path, download(webiew2_installer_url)?)?;
why was the logic, to check if it was already downloaded, got removed?

2023-11-23 16:04 UTC, i-c-b commented on tooling/bundler/src/bundle/windows/msi/wix.rs
> +      std::fs::write(&webview2_installer_path, download(webiew2_installer_url)?)?;
It was based on the input URL which is now static. We can get the final URL from the download `response` with a separate function and determine if the GUID has changed that way but this seems overkill if we were already prepared to fetch the bootstrapper each time.

2023-11-23 16:14 UTC, amrbashir commented on tooling/bundler/src/bundle/windows/msi/wix.rs
> +      std::fs::write(&webview2_installer_path, download(webiew2_installer_url)?)?;
no no, we download the offline installer in `%LOCALAPPDATA%/tauri` directory, and we skip downloading it second time if this file exists

2023-11-23 16:15 UTC, amrbashir commented on tooling/bundler/src/bundle/windows/msi/wix.rs
> +      std::fs::write(&webview2_installer_path, download(webiew2_installer_url)?)?;
Ah wait, I see what you mean, we don't need to store it in `%LOCALAPPDATA%/tauri/guid/arch` anymore IMO, it can just be `%LOCALAPPDATA%/tauri/arch`

2023-11-23 16:16 UTC, amrbashir commented on tooling/bundler/src/bundle/windows/msi/wix.rs
> +      std::fs::write(&webview2_installer_path, download(webiew2_installer_url)?)?;
and then keep the same check, because the offline installer is 100mb iirc and downloading that each time is a no no.

2023-11-23 16:23 UTC, i-c-b commented on tooling/bundler/src/bundle/windows/msi/wix.rs
> +      std::fs::write(&webview2_installer_path, download(webiew2_installer_url)?)?;
A HEAD request would be sufficient to get the final URL and crawl the existing GUID paths. If we don't find it, then do the full GET to download.

2023-11-23 16:26 UTC, amrbashir commented on tooling/bundler/src/bundle/windows/msi/wix.rs
> +      std::fs::write(&webview2_installer_path, download(webiew2_installer_url)?)?;
we don't need the GUID anymore, we can skip it

2023-11-23 22:21 UTC, i-c-b commented on tooling/bundler/src/bundle/windows/msi/wix.rs
> +      std::fs::write(&webview2_installer_path, download(webiew2_installer_url)?)?;
Wouldn't skipping the GUID cause an outdated installer to be used until the `target` directory is cleaned up? It would be fine for end users in online environments because Edge would update itself but an outdated installer in an offline environment could lead to confusion.

2023-11-23 22:26 UTC, amrbashir commented on tooling/bundler/src/bundle/windows/msi/wix.rs
> +      std::fs::write(&webview2_installer_path, download(webiew2_installer_url)?)?;
yeah right, then I guess your suggesting about querying the final URL is the way to go

2023-11-27 16:39 UTC, amrbashir requested changes

2023-11-27 16:39 UTC, amrbashir commented on tooling/bundler/src/bundle/windows/msi/wix.rs
> +      let (guid, filename) = webview2_guid_path(WEBVIEW2_BOOTSTRAPPER_URL)?;
this logic of downloading the installers seems to be repeated between nsis, and wix, let's move it into a function in `util.rs`

2023-11-28 02:26 UTC, i-c-b commented on tooling/bundler/src/bundle/windows/util.rs
> +  } else {
Should `arm64` be included here? Microsoft provides a separate arm64 version of the offline installer.

2023-11-28 22:58 UTC, amrbashir commented on tooling/bundler/src/bundle/windows/util.rs
> +  } else {
as @FabianLars mentioned, windows 11 on arm uses x86 so we will stick with that for now I guess

2023-11-28 23:07 UTC, amrbashir requested changes
I apologize for requesting a lot of changes but I think we are close to merge this

2023-11-28 23:07 UTC, amrbashir commented on tooling/bundler/src/bundle/windows/nsis.rs
> +        download_webview2(tauri_tools_path, WEBVIEW2_BOOTSTRAPPER_URL)?;
I think this can be just refactored to be
```rs
download_webview2_bootstrapper(tauri_tools_path);
```

Becasue the bootstrapper doesn't need to be stored in `<arch>/<guid>`, when invoked, it will always download the latest runtime, so it is okay if this file gets a bit outdated.

2023-11-28 23:07 UTC, amrbashir commented on tooling/bundler/src/bundle/windows/nsis.rs
> +      let webview2_installer_path = download_webview2(&base_path, url)?;
same here, this could be 
```rs
download_webview2_offline_installer(tauri_tools_path.join(arch));
```

2023-11-28 23:07 UTC, amrbashir requested changes
I apologize for requesting a lot of changes but I think we are close to merge this

2023-11-28 23:16 UTC, i-c-b commented on tooling/bundler/src/bundle/windows/nsis.rs
> +        download_webview2(tauri_tools_path, WEBVIEW2_BOOTSTRAPPER_URL)?;
Wouldn't splitting it into two functions with identical code except the URL be similar to the duplication we had before in NSIS and WiX?

2023-11-28 23:30 UTC, amrbashir commented on tooling/bundler/src/bundle/windows/nsis.rs
> +        download_webview2(tauri_tools_path, WEBVIEW2_BOOTSTRAPPER_URL)?;
I was only concerned between the duplication in nsis/wix but not between the two installer types. and realistically the code that will be duplicated would probably just be the request call which is fine IMO.

2023-11-29 01:46 UTC, amrbashir approved these changes
Thanks, LGTM now

2023-11-29 01:51 UTC, merged