chore: replace `once_cell` with `std::sync::OnceLock`
tauri-apps/tauri pull request #8309
Opened 2023-11-27 08:35 UTC by cijiugechu

### What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information
Since Rust 1.70, [once_cell::sync::OnceCell](https://docs.rs/once_cell/latest/once_cell/sync/struct.OnceCell.html), from the `once_cell` crate got integrated into the standard library as [std::sync::OnceLock](https://doc.rust-lang.org/std/sync/struct.OnceLock.html).

2023-11-27 12:39 UTC, FabianLars submitted a review, later dismissed

2023-11-27 15:24 UTC, amrbashir requested changes
Thanks for your contribution, just two small nit-picks and this should be good to go

2023-11-27 15:24 UTC, amrbashir commented on tooling/cli/src/helpers/app_paths.rs
> +static APP_DIR: OnceLock<PathBuf> = OnceLock::new();
why was this moved? just keep it at the same place as before

2023-11-27 15:24 UTC, amrbashir commented on tooling/cli/src/helpers/config.rs
> +static CONFING_HANDLE: OnceLock<ConfigHandle> = OnceLock::new();
same

2023-11-27 15:24 UTC, amrbashir commented on tooling/cli/src/helpers/config.rs
> +static CONFING_HANDLE: OnceLock<ConfigHandle> = OnceLock::new();
while you're at it, could you also fix the typo here? `CONFING` -> `CONFIG`

2023-11-28 01:06 UTC, amrbashir requested changes

2023-11-28 01:06 UTC, amrbashir commented on tooling/cli/src/helpers/app_paths.rs
> +
```suggestion
```

2023-11-28 01:06 UTC, amrbashir commented on tooling/cli/src/helpers/config.rs
> +
```suggestion
```

2023-11-28 01:08 UTC, amrbashir approved these changes
Thanks for your contributions.

2023-11-28 23:12 UTC, merged