feat(cli): improve error message with invalid target for `build`
tauri-apps/tauri pull request #8321
Opened 2023-11-30 17:49 UTC by KekmaTime

### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [x] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information

2023-11-30 17:54 UTC, KekmaTime commented
This updated part of code splits the target triple into components using split('-') and puts them into a vector. Then, it checks if the vector has the expected number of components (in this case three). If not, it prints an error message to the console and returns an empty Hashmap.

2023-11-30 18:45 UTC, amrbashir requested changes

2023-11-30 18:45 UTC, amrbashir commented on tooling/cli/src/interface/rust.rs
> +        eprintln!("Invalid Target Tuple: {}", target_triple);
```suggestion
        log::warn!("Invalid target triple: {}", target_triple);
```

2023-11-30 18:45 UTC, amrbashir commented on tooling/cli/src/interface/rust.rs
> +    let target_triple = self.app_settings.target_triple.clone();
I think you shouldn't need to clone here
```suggestion
    let target_triple = self.app_settings.target_triple;
```

2023-12-11 21:38 UTC, amrbashir submitted a review, later dismissed

2023-12-11 22:06 UTC, amrbashir approved these changes

2023-12-11 22:06 UTC, merged

2023-12-11 22:06 UTC, amrbashir commented
Thank you