feat(cli) rewrite the core CLI in Rust
tauri-apps/tauri pull request #851
Opened 2020-07-18 14:19 UTC by lucasfernog

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] New Binding Issue #___
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `latest` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

2020-07-21 18:24 UTC, tensor-programming requested changes

2020-07-21 18:24 UTC, tensor-programming commented on cli/tauri-bundler/src/bundle.rs
> +          Command::new("powershell")
should be `std::process::Command::new("powershell")` and remove `.force_prompt(true)`

2020-08-22 17:20 UTC, jbolda commented
to finish up the rust CLI PR, it seems we need to:
- hook up to node cli
- update branch with changes in dev
- add image support to rust inliner
    - we moved to a new crate from tauri-inliner
    - new crate doesn't have this, so we need to write it in rust

We may want to merge this into a separate feature branch and have these bullet points as separate points.

2021-01-27 03:23 UTC, lucasfernog commented
This PR is almost ready, just need to implement the old `dev` and `build` JS API for the commands (used by the unit tests and the vue-cli plugin).

2021-01-30 06:59 UTC, nothingismagick approved these changes

2021-01-30 15:15 UTC, merged