fix: target specific window for CLOSE_REQUESTED_EVENT emission
tauri-apps/tauri pull request #8826
Opened 2024-02-09 00:35 UTC by vonPB

When using the [onCloseRequested JS Api](https://github.com/tauri-apps/tauri/blob/cf3e40cc473dd0bb77f759fd59c1594af263429b/tooling/api/src/window.ts#L1689C29-L1689C39) the even was triggered even when other webviews were closed. 

It think it would

2024-02-09 00:47 UTC, amrbashir requested changes
Nice catch, I believe all window events should use `emit_filter` and target, `EventTarget::Any`, `EventTarget::Window` and `EventTarget::WebviewWindow`

2024-02-09 15:48 UTC, vonPB commented
> Nice catch, I believe all window events should use `emit_filter` and target, `EventTarget::Any`, `EventTarget::Window` and `EventTarget::WebviewWindow`

Thanks for the feedback @amrbashir, I've changed the `emit_to` to `emit_filter`.
However, I'm curious about your suggestions to use `EventTarget::Any` as well. Wouldn't `Any` already target the others inherently? This would also continue to send the close requested event to all windows...

Or did you just mean to say that all events should use emit_filter?

2024-02-10 00:33 UTC, amrbashir commented
You're right, no need to target `EventTarget::Any`, I suggested that so the event would still trigger listeners from `app.listen_any` but it will be emitted to it anyway. For this PR, `EventTarget::Window` and `EventTarget::WebviewWindow` should be enough.

2024-02-10 01:06 UTC, vonPB commented
Ah, gotcha. So even if there is no matching`Window` or `WebviewWindow` the event should still be emitted internally for `listen_any` to catch, right? https://github.com/tauri-apps/tauri/pull/8826/commits/257e95b218ca1bf9b543d644a94f1136f4614b53

2024-02-12 15:54 UTC, amrbashir approved these changes
Thank you

2024-02-12 15:55 UTC, merged