fix(event): clear residual listeners (#8916 )
tauri-apps/tauri pull request #8930
Opened 2024-02-21 11:49 UTC by canxin121

fix clear residual listeners, close #8916 

I noticed that in v1, `js_listeners` were stored on the frontend, so refreshing the page cleans up the original `js_listeners` (note that this doesn't mean that useEffect cleans up the side-effects, as it doesn't have a way to clean up the side-effects before refreshing the page).

However, in v2, `js_listeners` are stored not only in the front end, but also in the back end, and the number of events triggered is determined by the `js_listeners` that stored in the backend, which results in a pileup of `js_listeners` that can't be cleaned up when the page is refreshed.

I added a new js command `unlisten_all` and invoke it at the end of `core.js` to solve this problem. `unlisten_all` only cancels the `js_listeners` at the frontend and backend of the *current window*. 

This fix works fine on my machine, in both single-window and multi-window scenarios.

2024-02-21 12:18 UTC, canxin121 commented
[A fixed demo](https://github.com/canxin121/test_listen_v2)

https://github.com/tauri-apps/tauri/assets/69547456/b1a34d18-f9f7-43fe-b918-867ca651a0ae


The origin error demo can be seen at #8916

2024-02-23 07:18 UTC, canxin121 commented
I just signed the initial commit( dab5723) using `git rebase ---signoff`.

2024-02-26 16:28 UTC, lucasfernog commented
I think there's a better way to do this. Handling this via a command called by the frontend might lead to race conditions.
What we could do instead is modify [this closure](https://github.com/tauri-apps/tauri/blob/bc5b5e671a546512f823f1c157421b4c3311dfc0/core/tauri/src/webview/mod.rs#L575) and clear the listeners when the page starts to load.

2024-02-27 10:05 UTC, canxin121 commented
> I think there's a better way to do this. Handling this via a command called by the frontend might lead to race conditions. What we could do instead is modify [this closure](https://github.com/tauri-apps/tauri/blob/bc5b5e671a546512f823f1c157421b4c3311dfc0/core/tauri/src/webview/mod.rs#L575) and clear the listeners when the page starts to load.

Very good suggestion, I hadn't thought of fixing this bug here before, and now that I've rewritten a new version which doesn't involve any front-end code and no more `unlisten_all_js` for `tauri::command`, it should work as expected.

2024-02-27 23:26 UTC, vonPB commented
Been using this for today's development and had no issues at all :)

2024-02-28 15:57 UTC, amrbashir requested changes

2024-02-28 15:57 UTC, amrbashir commented on core/tauri/src/event/listener.rs
> +  }
We can just call `.remove(webview_label)`
```suggestion
  pub(crate) fn unlisten_all_js(&self, webview_label: &str) {
    let inner_listeners = self.inner.as_ref();
    let mut js_listeners = inner_listeners.js_event_listeners.lock().unwrap();
    js_listeners.remvoe(webview_label);
  }
```

2024-02-28 15:57 UTC, amrbashir commented on core/tauri/src/event/mod.rs
> +pub fn unlisten_all_js_script(listeners_object_name: &str) -> String {
this shouldn't be necessary, since reloads will clear the `window` objects.

2024-02-28 15:57 UTC, amrbashir commented on core/tauri/src/webview/mod.rs
> +    self.eval(&crate::event::unlisten_all_js_script(
same as above, should not be necessary

2024-02-28 15:57 UTC, amrbashir commented on core/tauri/src/webview/mod.rs
> +            };
Should be okay to ignore the error here.
```suggestion
            let _ = w.unlisten_all_js();
```

2024-02-28 16:48 UTC, amrbashir approved these changes, later dismissed

2024-02-28 18:26 UTC, amrbashir approved these changes

2024-02-28 18:26 UTC, merged

2024-02-28 18:26 UTC, amrbashir commented
Thank you

2024-03-08 19:27 UTC, samkearney commented
I'm not sure if this is expected, but this change seems to be causing some kind of race condition on initial load of a React page. I am calling listen() from the componentDidMount() function of a React component. From my debugging it seems like the following order of events is happening:

1. Page begins to load, componentDidMount() is called, my code calls listen() and registers a listener
2. Tauri considers the page to be "ready". The `on_page_load_handler` is called, and hits a breakpoint inside the function that was added in this PR, `unlisten_all_js()`. This clears the listener my page had registered.
3. Later, my backend code emits some events, but there is nothing to listen to them.

I am new to Tauri, so I may be doing something wrong, but is this expected?

2024-03-08 19:34 UTC, FabianLars commented
Hmm, i highly doubt that componentDidMount triggers before DOMContentLoaded. Not 100% sure but still feels wrong to me.

Can you share the code where you listen to and emit the event?

2024-03-08 19:39 UTC, samkearney commented
It's closed-source, but let me try to reduce it to something minimal. While I work on that, could you point me to any advice or best practices for places in the lifecycle of a React page where it makes the most sense to set up event listening?

2024-03-08 20:07 UTC, FabianLars commented
componentDidMount or useEffect with [] is indeed correct. You just have to unlisten to the event on unmount too. An example for that with useEffect (because i didn't use componentDidMount for years) looks like this
```ts
useEffect(() => {
  const unlisten = listen("someevent", console.log);
  
  return () => {
    unlisten.then( f => f() );
  }
}, []);
```

2024-03-08 20:58 UTC, samkearney commented
My minimal reproducer still shows weird behavior, it is not exactly the same as the behavior I described in our larger app code, but it seems like events are arriving out of order and/or there are duplicate copies of some events.

React:
```tsx
import { useEffect, useState } from "react";
import reactLogo from "./assets/react.svg";
import "./App.css";
import { listen } from "@tauri-apps/api/event";

interface EventPayload {
  number: number;
}

function App() {
  const [number, setNumber] = useState(0);

  useEffect(() => {
    const unlisten = listen<EventPayload>("myEvent", (event) => {
      console.log(`Got event: ${event.payload.number}`);
      setNumber(event.payload.number);
    });

    return () => {
      unlisten.then((f) => f());
    };
  }, []);

  return (
    <div className="container">
      <h1>Welcome to Tauri!</h1>

      <div className="row">
        <a href="https://vitejs.dev" target="_blank">
          <img src="/vite.svg" className="logo vite" alt="Vite logo" />
        </a>
        <a href="https://tauri.app" target="_blank">
          <img src="/tauri.svg" className="logo tauri" alt="Tauri logo" />
        </a>
        <a href="https://reactjs.org" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>

      <p>Click on the Tauri, Vite, and React logos to learn more.</p>

      <p>Number: {number}</p>
    </div>
  );
}

export default App;
```

Rust:
```rs
// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use std::{thread, time::Duration};

use serde::Serialize;
use tauri::{EventTarget, Manager};

#[derive(Clone, Debug, Serialize)]
struct EventPayload {
    number: i32,
}

fn main() {
    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .on_page_load(|page, _| {
            let app_handle = page.app_handle().clone();
            thread::spawn(move || {
                let mut number: i32 = 1;

                loop {
                    app_handle
                        .emit_to(
                            EventTarget::webview_window("main"),
                            "myEvent",
                            EventPayload { number },
                        )
                        .unwrap();
                    number += 1;
                    thread::sleep(Duration::from_millis(50));
                }
            });
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

Results (notice the slight stuttering, this is sometimes better or worse)
![stuttering_number](https://github.com/tauri-apps/tauri/assets/5142299/b201187b-5348-4af7-bb2b-bd947696a802)

Snippet from console log:

```
App.tsx:15 Got event: 170
App.tsx:15 Got event: 175
App.tsx:15 Got event: 171
App.tsx:15 Got event: 176
App.tsx:15 Got event: 172
App.tsx:15 Got event: 177
App.tsx:15 Got event: 173
App.tsx:15 Got event: 178
App.tsx:15 Got event: 174
App.tsx:15 Got event: 179
App.tsx:15 Got event: 175
App.tsx:15 Got event: 180
App.tsx:15 Got event: 181
App.tsx:15 Got event: 176
App.tsx:15 Got event: 182
App.tsx:15 Got event: 177
App.tsx:15 Got event: 178
App.tsx:15 Got event: 183
App.tsx:15 Got event: 179
App.tsx:15 Got event: 184
App.tsx:15 Got event: 180
App.tsx:15 Got event: 185
App.tsx:15 Got event: 181
App.tsx:15 Got event: 186
App.tsx:15 Got event: 182
App.tsx:15 Got event: 187
App.tsx:15 Got event: 183
App.tsx:15 Got event: 188
App.tsx:15 Got event: 184
App.tsx:15 Got event: 189
App.tsx:15 Got event: 185
App.tsx:15 Got event: 190
App.tsx:15 Got event: 186
App.tsx:15 Got event: 191
App.tsx:15 Got event: 187
App.tsx:15 Got event: 192
App.tsx:15 Got event: 188
App.tsx:15 Got event: 193
App.tsx:15 Got event: 189
App.tsx:15 Got event: 194
App.tsx:15 Got event: 190
App.tsx:15 Got event: 195
App.tsx:15 Got event: 191
App.tsx:15 Got event: 196
App.tsx:15 Got event: 192
App.tsx:15 Got event: 197
App.tsx:15 Got event: 198
App.tsx:15 Got event: 193
```

Almost seems like there are two copies of each event being delivered.

2024-03-08 21:45 UTC, samkearney commented
In making my minimal reproducer I realized I had several incorrect assumptions about my code. I think things are working now. Apologies for the spam.

2024-03-10 09:18 UTC, gulbanana commented
Here's a repro demonstrating a bug where the listeners are cleaned up too late, destroying new callbacks that were just installed. For me, this works on Windows and on MacOS dev builds, but fails on MacOS production builds.
https://github.com/gulbanana/repro-tauri-macos-events