feat(cli): add macos signing config option
tauri-apps/tauri pull request #9318
Opened 2024-03-31 21:04 UTC by thewh1teagle

In `macOS`, when building `dmg` with `ad-hoc` signature, and the app depends on Frameworks (dynamic shared libraries, `dylib` files), they won't load and the app will crash with error message box.

I found that if we disable signing flag in `macOS` bundler passed from `tauri-cli`, it won't crash.
the flag which passed is `--option runtime` in [tooling/bundler/src/bundle/macos/sign.rs#L210](https://github.com/tauri-apps/tauri/blob/dev/tooling/bundler/src/bundle/macos/sign.rs#L210)

<details>
<summary>crash log</summary>

```
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/libavcodec.60.dylib
Referenced from: <D007FD2C-8AD0-336A-944D-C186621D1CEF> /Volumes/VOLUME/vibe.app/Contents/MacOS/vibe
Reason: tried: '/Volumes/vibe/vibe.app/Contents/Frameworks/libavcodec.60.dylib' (code signature in <BEFA8967-6321-3361-9151-FF5EE424F751> '/Volumes/vibe/vibe.app/Contents/Frameworks/libavcodec.60.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/Volumes/vibe/vibe.app/Contents/Frameworks/libavcodec.60.dylib' (code signature in <BEFA8967-6321-3361-9151-FF5EE424F751> '/Volumes/vibe/vibe.app/Contents/Frameworks/libavcodec.60.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs)
(terminated at launch; ignore backtrace)
```
</details>

<details>

<summary>man codesign</summary>

```
     -o, --options flag,...
             During signing, specifies a set of option flags to be embedded in
             the code signature. The value takes the form of a comma-separated
             list of names (with no spaces). Alternatively, a numeric value
             can be used to directly specify the option mask (CodeDirectory
             flag word). See OPTION FLAGS below.

Flags:
             runtime              Preserve the hardened runtime version (-o
                                  runtime flag, --runtime-version option)
                                  instead of overriding or deriving the
                                  version.
```

</details>

This PR introduce a way to control the flag through `tauri.conf.json`:
```json
  "bundle": {
    "macOS": {
      "signingIdentity": "-",
      "signingRuntimeFlag": false
    }
  }
```

2024-05-15 12:57 UTC, thewh1teagle commented
Just a gentle reminder: I'm currently unable to test my app build locally due to the damaged `dmg` release caused by the default `hardened` option. It's impacting my development process. Any chance we could prioritize merging the PR? Appreciate your attention to this matter!

2024-06-03 03:42 UTC, cismous2204 commented
Especially useful, can anyone review and merge it? Thank you very much!

2024-06-05 15:41 UTC, FabianLars requested changes
Thanks, just some smaller things and then it's good to go :)

2024-06-05 15:41 UTC, FabianLars commented on core/tauri-utils/src/config.rs
> +      hardened_runtime: hardened_runtime(),
```suggestion
      hardened_runtime: true,
```

2024-06-05 15:41 UTC, FabianLars commented on core/tauri-utils/src/config.rs
> +  #[serde(alias = "hardened-runtime", default = "hardened_runtime")]
```suggestion
  #[serde(alias = "hardened-runtime", default = "default_true")]
```

Just re-use the default_true function from (defined at the top of the file)

2024-06-05 15:41 UTC, FabianLars commented on core/tauri-utils/src/config.rs
> +
```suggestion
```
With the 2 other changes this can be removed again

2024-06-05 16:02 UTC, thewh1teagle commented
Thanks for the review : - )
Edited as suggested

2024-06-05 16:03 UTC, FabianLars approved these changes

2024-06-05 16:04 UTC, merged