feat: Expose webview2 zoom hotkeys from wry
tauri-apps/tauri pull request #9352
Opened 2024-04-03 06:08 UTC by Legend-Master

Closes: #3310

2024-04-03 15:30 UTC, amrbashir requested changes
Just a few documentation nitpicks. You will need to regenerate the schema file.

2024-04-03 15:30 UTC, amrbashir commented on core/tauri-utils/src/config.rs
> +  /// **macOS / Linux / Android / iOS**: Unsupported
```suggestion
  /// Whether page zooming by hotkeys is enabled **Windows Only**
```

2024-04-03 15:30 UTC, amrbashir commented on core/tauri/src/webview/mod.rs
> +  /// **macOS / Linux / Android / iOS**: Unsupported
```suggestion
  /// Whether page zooming by hotkeys is enabled **Windows Only**
```

2024-04-03 15:30 UTC, amrbashir commented on core/tauri/src/webview/webview_window.rs
> +  /// **macOS / Linux / Android / iOS**: Unsupported
```suggestion
  /// Whether page zooming by hotkeys is enabled **Windows only**
```

2024-04-03 15:30 UTC, amrbashir commented on tooling/api/src/webview.ts
> +   * - **macOS / Linux / Android / iOS**: Unsupported
```suggestion
   * Whether page zooming by hotkeys or gestures is enabled **Windows Only**
```

2024-04-03 15:52 UTC, lucasfernog commented
Can we use [WebView::zoom](https://docs.rs/wry/latest/wry/struct.WebView.html#method.zoom) to manually implement this feature on macOS/Linux?

2024-04-03 16:03 UTC, amrbashir approved these changes

2024-04-03 16:04 UTC, amrbashir commented
This PR is for only allowing users to enable the builtin one on Webview2, we need another PR to expose [WebView::zoom](https://docs.rs/wry/latest/wry/struct.WebView.html#method.zoom) and users can create a UI for it themselves.

2024-04-03 16:10 UTC, amrbashir commented
hmm actually this doesn't enable any UI, just the hotkeys, maybe we can indeed emulate the behavior on other platforms and also expose [WebView::zoom](https://docs.rs/wry/latest/wry/struct.WebView.html#method.zoom) at the same time

@Legend-Master would you like to add that too in this PR?

2024-04-03 16:29 UTC, Legend-Master commented
I think it's fine to expose the webview2 one first in this pr (it's in the webview2 api but we don't have a way to use it), and expose zoom function and polyfill for this functionality in another pr

If we want to put them in a single pr, I can take a look tomorrow, but I'm not familiar with WebKit zoom controls (is it the same as Chromium?)

2024-04-03 18:12 UTC, amrbashir commented
> If we want to put them in a single pr, I can take a look tomorrow, but I'm not familiar with WebKit zoom controls (is it the same as Chromium?)
> 
> And emulating it would be injecting some JavaScript to the webview?

Yeah should be the same keys, `ctrl +/-`.

2024-04-03 18:14 UTC, merged

2024-04-04 02:08 UTC, Legend-Master commented
Seems like webview2 zoom popup is disabled without a way to getting it back https://github.com/MicrosoftEdge/WebView2Feedback/issues/95#issuecomment-591590945, also the zoom factor is not persisted across page load (reset to 100% on reload/restart), pretty sad that webview2's zoom control is a downgraded version of the browser zoom control 😥