feat(tray): add `TrayIcon::rect` method
tauri-apps/tauri pull request #9615
Opened 2024-04-30 13:56 UTC by pronebird

Follow up PR on https://github.com/tauri-apps/tray-icon/pull/147

2024-04-30 14:02 UTC, amrbashir requested changes
Could you also add a change file in `.changes` directory?

2024-04-30 14:02 UTC, amrbashir commented on core/tauri/src/tray/mod.rs
> +  }
```suggestion
  
  /// Get tray icon rect.
  ///
  /// ## Platform-specific:
  ///
  /// - **Linux**: Unsupported, always returns `None`.
  pub fn rect(&self) -> crate::Result<Option<crate::Rect>> {
    run_item_main_thread!(self, |self_: Self| self_.inner.rect().map(
      |rect| {
        Rect {
          position: rect.position.into(),
          size: rect.size.into(),
        }
      }
    ))
  }
```

2024-04-30 14:05 UTC, pronebird commented
> Thank you, Could you also add a change file in `.changes` directory?

In a minute

2024-04-30 14:17 UTC, pronebird commented
Not sure how exactly you name `.md` files under `changes/`. Please have another look.

2024-04-30 14:24 UTC, amrbashir commented on .changes/tray-icon-rect.md
> +"tauri": "feat"
```suggestion
"tauri": "minor:feat"
```

2024-04-30 14:25 UTC, amrbashir commented
Once a new release of tray-icon crate is made, we can merge this

2024-05-03 02:39 UTC, amrbashir submitted a review, later dismissed

2024-05-03 02:50 UTC, amrbashir approved these changes

2024-05-03 02:56 UTC, merged

2024-05-03 02:56 UTC, amrbashir commented
Thank you