fix(windows): nsis failed to resolve resources with `$` in their name. closes #9657
tauri-apps/tauri pull request #9659
Opened 2024-05-05 07:44 UTC by enkhjile

Registering a global escape function that replaces `$` with `$$` in Handlebars causes the build step to fail when resources contain `$` in their names, because NSIS commands like `File /a` cannot resolve the escaped paths. #9657

I've added a helper that unescapes `$$` back to `$` and modified the corresponding resource expression in `installer.nsi` to use this helper.

If there are better solutions, I'd be happy to implement them.

2024-05-07 14:15 UTC, amrbashir commented
Thanks for your contributions. I did a bit of experiments and seems like only the input to `File`, needs unescaped values so please revert changes to other places, also could you run `cargo fmt` inside `tooling/bundler`?

2024-05-08 03:45 UTC, enkhjile commented
@amrbashir 
Thanks for your feedback. I have reverted the changes to the `installer.nsi`, except for the `File` sections, and have run `cargo fmt`.

2024-05-08 17:14 UTC, amrbashir requested changes
Thank you, just a couple of more to go

2024-05-08 17:14 UTC, amrbashir commented on tooling/bundler/src/bundle/windows/templates/installer.nsi
> +    File /a "/oname={{unescape-dollar-sign this.[1]}}" "{{unescape-dollar-sign @key}}"
no need to unescape in `/oname` portion

2024-05-08 17:14 UTC, amrbashir commented on tooling/bundler/src/bundle/windows/templates/installer.nsi
> +    File /a "/oname={{unescape-dollar-sign this}}" "{{unescape-dollar-sign @key}}"
no need to unescape in `/oname` portion

2024-05-08 17:26 UTC, amrbashir commented on tooling/bundler/src/bundle/windows/templates/installer.nsi
> +    File /a "/oname={{unescape-dollar-sign this}}" "{{unescape-dollar-sign @key}}"
```suggestion
    File /a "/oname={{this}}" "{{unescape-dollar-sign @key}}"
```

2024-05-08 17:26 UTC, amrbashir commented on tooling/bundler/src/bundle/windows/templates/installer.nsi
> +    File /a "/oname={{unescape-dollar-sign this.[1]}}" "{{unescape-dollar-sign @key}}"
```suggestion
    File /a "/oname={{this.[1]}}" "{{unescape-dollar-sign @key}}"
```

2024-05-08 17:27 UTC, amrbashir submitted a review, later dismissed
Thank you

2024-05-08 17:29 UTC, amrbashir approved these changes

2024-05-08 17:32 UTC, merged