feat(bundler): support custom sign command on Windows
tauri-apps/tauri pull request #9902
Opened 2024-05-29 07:51 UTC by muwoo

feat: Migrate v2 functionality to v1.x: support custom sign command on Windows (Discussed in https://github.com/tauri-apps/tauri/discussions/9900)

- [x] cargo test passes
- [x] cargo clippy passes

2024-05-30 19:23 UTC, amrbashir approved these changes

2024-05-30 20:03 UTC, amrbashir requested changes
Looks like you need to run `cargo fmt` and `cargo clippy -- -Dwarnings`

2024-06-03 03:11 UTC, muwoo commented
> Looks like you need to run `cargo fmt` and `cargo clippy -- -Dwarnings`

done

2024-06-03 18:34 UTC, amrbashir approved these changes

2024-06-03 18:34 UTC, merged

2024-06-04 04:07 UTC, MystiPanda reviewed
Maybe it needs to be modified here.

2024-06-04 04:07 UTC, MystiPanda commented on tooling/bundler/src/bundle/windows/nsis.rs
> +    create_dir_all(&nsis_toolset_path)?;
Creating an NSIS folder in advance will cause subsequent renaming failures after decompression

```rust
rename(_tauri_tools_path.join("nsis-3.08"), nsis_toolset_path)?;
```

2024-06-27 20:03 UTC, tr3ysmith commented
@amrbashir any thoughts on when v1.7 would be released that contains this fix?

2024-06-28 11:52 UTC, amrbashir commented
I don't want to make promises but hopefully this week

2024-07-02 18:15 UTC, tr3ysmith commented
@amrbashir I see 1.7 came out, but I don't see anything about this feature in the release notes, is it indeed in there?

2024-07-02 18:28 UTC, amrbashir commented
@tr3ysmith here it is https://github.com/tauri-apps/tauri/releases/tag/tauri-bundler-v1.6.0

2024-07-02 22:00 UTC, ttrushin commented
Maybe a silly question, but I have tauri updated to 1.7.1 (and tauri-build updated to 1.5.3) so everything appears to be updated to latest, but I cannot build with "signCommand". 

```Error `tauri.conf.json` error on `tauri > bundle > windows`: Additional properties are not allowed ('signCommand' was unexpected)```

Anyone know why?

2024-07-03 01:19 UTC, amrbashir commented
make sure to also update the CLI