feat(bundler): Add `provides` `conflicts` `replaces` field for `deb` control file.
tauri-apps/tauri pull request #9942
Opened 2024-06-02 08:13 UTC by Pylogmon

This PR aims to add the `provides`, `conflicts`, and `replaces` configuration options for Debian Packages, allowing developers to include these fields in custom Debian Packages.

2024-06-03 18:49 UTC, amrbashir commented on .changes/deb-rpm-provides-conflicts-replaces.md
> +'tauri-cli': 'minor:feat'
```suggestion
'tauri-cli': 'minor:feat'
'@tauri-apps/cli: 'minor:feat'
```

2024-06-03 18:50 UTC, amrbashir submitted a review, later dismissed

2024-06-03 18:55 UTC, amrbashir commented on .changes/deb-rpm-provides-conflicts-replaces.md
> +'@tauri-apps/cli: 'minor:feat'
```suggestion
'@tauri-apps/cli': 'minor:feat'
```

2024-06-03 18:56 UTC, amrbashir approved these changes

2024-06-03 18:57 UTC, amrbashir commented
looks like you need to fix `cargo fmt` and `cargo clippy`, thanks for contribution

2024-06-03 18:57 UTC, amrbashir requested changes
looks like you need to fix `cargo fmt` and `cargo clippy`, thanks for contribution

2024-06-04 01:28 UTC, Pylogmon commented
BTW, if I want to use the latest feature before the next 1.x release, what should I do? In `Cargo.toml`, I can directly rely on git, but I don't know what to do in `package.json`.

2024-06-04 01:30 UTC, amrbashir commented
Checkout https://tauri.app/v1/guides/faq

2024-06-04 01:37 UTC, amrbashir approved these changes, later dismissed

2024-06-04 01:38 UTC, amrbashir commented on .changes/deb-rpm-provides-conflicts-replaces.md
> +'@tauri-apps/cli': 'minor:feat'
```suggestion
```

2024-06-04 01:38 UTC, amrbashir approved these changes

2024-06-04 01:47 UTC, merged

2024-06-04 01:47 UTC, amrbashir commented
Thanks for contribution

2024-06-09 14:40 UTC, Zylsjsp commented
Will there be a cherry-pick into branch `1.6` for the backport please? Or it's not planned in 1.6.x yet?

2024-06-09 16:16 UTC, amrbashir commented
No, it will be in 1.7